name: Run Tests

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo
        ports: 
          - 27017:27017

    steps:
    - uses: actions/checkout@v2

    # Backend tests
    - name: Use Node.js for backend
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Install Dependencies for backend
      run: cd backend && npm ci

    - name: Run tests for backend
      run: cd backend && npm test

    # Frontend tests
    - name: Use Node.js for frontend
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Install Dependencies for frontend
      run: cd frontend && npm ci

    - name: Start frontend server
      run: |
        cd frontend
        npm start &
        sleep 15

    - name: Run tests for frontend
      run: cd frontend && npm run cy:test