name: Continuous Integration

on: [push]

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Run mongo container
      run: docker run -d -p 27017:27017 mongo

    - name: Install backend dependencies
      run: |
        cd backend
        npm install

    - name: Run backend tests
      run: |
        cd backend
        npm run test

  frontend:
    needs: backend
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install frontend dependencies
      run: |
        npm install
        npm install start-server-and-test --save-dev

    - name: Run frontend development mode and cypress tests
      run: |
        cd frontend
        npm run dev &
        npx start-server-and-test http://localhost:5173 cy:test