name: Continuous Integration

on: [push]

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js environment
      uses: actions/setup-node@v4

    - name: Run mongo container
      run: docker run -d -p 27017:27017 mongo

    - name: Install backend dependencies
      run: |
        cd backend
        npm install

    - name: Run backend tests and generate coverage report
      run: |
        cd backend
        npm run test

    - name: Publish coverage report
      uses: actions/upload-artifact@v4
      with:
        name: backend-coverage-report
        path: backend/coverage/

  frontend:
    needs: backend
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js environment
      uses: actions/setup-node@v2

    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install
        
    - name: Run frontend dev mode and cypress tests
      run: |
        cd frontend
        npm run dev &
    
    - name: Run cypress tests
      run: |
        cd frontend
        npx cypress run --headed